local Model = {
    Direction = {
        addr = 0xD4DE,
        size = 1,
        NORTH = 4,
        EAST = 12,
        SOUTH = 0,
        WEST = 8,
    },

    PositionX = {
        addr = 0xDCB8,
        size = 1,
    },

    PositionY = {
        addr = 0xDCB7,
        size = 1,
    },

    -- Is set when the current movement is blocked
    Collision = {
        addr = 0xC1DE,
        size = 1,
        NO_COLLISION = {0, 1} -- 2 values to represent no collision
    },

    MovementEnabled = {
        addr = 0xD434,
        size = 1,
        memdomain = Memory.WRAM,
        MOVEMENT_ENABLED = 0,
        MOVEMENT_DISABLED = 4
    },

    Motion = {
        addr = 0xD04E,
        size = 1,
        NO_MOTION = 0,
        NORTH = 129,
        EAST = 131,
        SOUTH = 128,
        WEST = 130
    },

    Bicycle = {
        addr = 0xD95D,
        size = 1,
        memdomain = "WRAM",
        ACTIVE = 1,
        INACTIVE = 0,
        moveFrames = 7,
        initialMoveFrame = 3,
        postMoveFrames = 5
    },

    Walking = {
        initialMoveFrame = 6, -- Total number of frames required to update coordinate in memory
        postMoveFrames = 10, -- Minimum frames required to initiate steps
    },

    Map = {
        addr = 0xC2D8,
        size = 1,
        NEWBARKTOWN = 1,
        ROUTE29 = 2,
        CHERRYGROVECITY = 3,
        ROUTE30 = 4,
        ROUTE31 = 5,
        VIOLETCITY = 6,
        SPROUTTOWER = 7,
        ROUTE32 = 8,
        RUINSOFALPH = 9,
        UNIONCAVE = 10,
        ROUTE33 = 11,
        AZALEATOWN = 12,
        SLOWPOKEWELL = 13,
        ILEXFOREST = 14,
        ROUTE34 = 15,
        GOLDENRODCITY = 16,
        RADIOTOWER = 17,
        ROUTE35 = 18,
        NATIONALPARK = 19,
        ROUTE36 = 20,
        ROUTE37 = 21,
        ECRUTEAKCITY = 22,
        TINTOWER = 23,
        BURNEDTOWER = 24,
        ROUTE38 = 25,
        ROUTE39 = 26,
        OLIVINECITY = 27,
        LIGHTHOUSE = 28,
        BATTLETOWER = 29,
        ROUTE40 = 30,
        WHIRLISLANDS = 31,
        ROUTE41 = 32,
        CIANWOODCITY = 33,
        ROUTE42 = 34,
        MTMORTAR = 35,
        MAHOGANYTOWN = 36,
        ROUTE43 = 37,
        LAKEOFRAGE = 38,
        ROUTE44 = 39,
        ICEPATH = 40,
        BLACKTHORNCITY = 41,
        DRAGONSDEN = 42,
        ROUTE45 = 43,
        DARKCAVE = 44,
        ROUTE46 = 45,
        SILVERCAVE = 46,
        PALLETTOWN = 47,
        ROUTE1 = 48,
        VIRIDIANCITY = 49,
        ROUTE2 = 50,
        PEWTERCITY = 51,
        ROUTE3 = 52,
        MTMOON = 53,
        ROUTE4 = 54,
        CERULEANCITY = 55,
        ROUTE24 = 56,
        ROUTE25 = 57,
        ROUTE5 = 58,
        UNDERGROUND = 59,
        ROUTE6 = 60,
        VERMILIONCITY = 61,
        DIGLETTSCAVE = 62,
        ROUTE7 = 63,
        ROUTE8 = 64,
        ROUTE9 = 65,
        ROCKTUNNEL = 66,
        ROUTE10 = 67,
        POWERPLANT = 68,
        LAVENDERTOWN = 69,
        LAVRADIOTOWER = 70,
        CELADONCITY = 71,
        SAFFRONCITY = 72,
        ROUTE11 = 73,
        ROUTE12 = 74,
        ROUTE13 = 75,
        ROUTE14 = 76,
        ROUTE15 = 77,
        ROUTE16 = 78,
        ROUTE17 = 79,
        ROUTE18 = 80,
        FUCHSIACITY = 81,
        ROUTE19 = 82,
        ROUTE20 = 83,
        SEAFOAMISLANDS = 84,
        CINNABARISLAND = 85,
        ROUTE21 = 86,
        ROUTE22 = 87,
        VICTORYROAD = 88,
        ROUTE23 = 89,
        INDIGOPLATEAU = 90,
        ROUTE26 = 91,
        ROUTE27 = 92,
        TOHJOFALLS = 93,
        ROUTE28 = 94,
        NEWBARKTOWNFASTSHIP = 95,
    },
}
return Model